/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addmaster;

import java.awt.image.ImageObserver;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Jaspreet Singh
 */
public class Masteradd extends javax.swing.JFrame {

    /**
     * Creates new form Masteradd
     */
    public Masteradd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmenu = new javax.swing.JPopupMenu();
        Entertainment = new javax.swing.JCheckBox();
        News = new javax.swing.JCheckBox();
        HD = new javax.swing.JCheckBox();
        Infotainment = new javax.swing.JCheckBox();
        Spiritual = new javax.swing.JCheckBox();
        Movies = new javax.swing.JCheckBox();
        LChannel = new javax.swing.JCheckBox();
        Kids = new javax.swing.JCheckBox();
        Music = new javax.swing.JCheckBox();
        Regional = new javax.swing.JCheckBox();
        mn = new javax.swing.JCheckBox();
        ms = new javax.swing.JCheckBox();
        das = new javax.swing.JCheckBox();
        ndas = new javax.swing.JCheckBox();
        Filemn = new javax.swing.JTextField();
        Filems = new javax.swing.JTextField();
        Filedas = new javax.swing.JTextField();
        Filendas = new javax.swing.JTextField();
        chname1 = new javax.swing.JTextField();
        Channel1 = new javax.swing.JCheckBox();
        Channel2 = new javax.swing.JCheckBox();
        Channel3 = new javax.swing.JCheckBox();
        Channel4 = new javax.swing.JCheckBox();
        Channel5 = new javax.swing.JCheckBox();
        chname2 = new javax.swing.JTextField();
        chname3 = new javax.swing.JTextField();
        chname4 = new javax.swing.JTextField();
        chname5 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ala1 = new javax.swing.JTextField();
        master1 = new javax.swing.JTextField();
        Lang1 = new javax.swing.JComboBox();
        BL1 = new javax.swing.JComboBox();
        ala2 = new javax.swing.JTextField();
        ala3 = new javax.swing.JTextField();
        ala4 = new javax.swing.JTextField();
        ala5 = new javax.swing.JTextField();
        master2 = new javax.swing.JTextField();
        master3 = new javax.swing.JTextField();
        master4 = new javax.swing.JTextField();
        master5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Lang2 = new javax.swing.JComboBox();
        Lang3 = new javax.swing.JComboBox();
        Lang4 = new javax.swing.JComboBox();
        Lang5 = new javax.swing.JComboBox();
        BL2 = new javax.swing.JComboBox();
        BL3 = new javax.swing.JComboBox();
        BL4 = new javax.swing.JComboBox();
        BL5 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        payfta1 = new javax.swing.JComboBox();
        payfta2 = new javax.swing.JComboBox();
        payfta3 = new javax.swing.JComboBox();
        payfta4 = new javax.swing.JComboBox();
        payfta5 = new javax.swing.JComboBox();
        Add = new javax.swing.JButton();
        Ga1 = new javax.swing.JComboBox();
        Gb1 = new javax.swing.JComboBox();
        Gc1 = new javax.swing.JComboBox();
        Ga2 = new javax.swing.JComboBox();
        Gb2 = new javax.swing.JComboBox();
        Gc2 = new javax.swing.JComboBox();
        Ga3 = new javax.swing.JComboBox();
        Gb3 = new javax.swing.JComboBox();
        Gc3 = new javax.swing.JComboBox();
        Ga4 = new javax.swing.JComboBox();
        Gb4 = new javax.swing.JComboBox();
        Gc4 = new javax.swing.JComboBox();
        Ga5 = new javax.swing.JComboBox();
        Gb5 = new javax.swing.JComboBox();
        Gc5 = new javax.swing.JComboBox();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        Entertainment.setText("Entertainment");

        News.setText("News and Learning");

        HD.setText("HD");

        Infotainment.setText("Infotainment");

        Spiritual.setText("Spiritual");

        Movies.setText("Movies");

        LChannel.setText("Local Channel");

        Kids.setText("Kids");

        Music.setText("Music");

        Regional.setText("Regional");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mn.setText("Master North");

        ms.setText("Master South");
        ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msActionPerformed(evt);
            }
        });

        das.setText("CA DAS Package");

        ndas.setText("CA NON-DAS Package");

        Filemn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilemnMouseClicked(evt);
            }
        });

        Filems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilemsMouseClicked(evt);
            }
        });

        Filedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiledasMouseClicked(evt);
            }
        });

        Filendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilendasMouseClicked(evt);
            }
        });

        Channel1.setText("Channel 1");

        Channel2.setText("Channel 2");

        Channel3.setText("Channel 3");

        Channel4.setText("Channel 4");

        Channel5.setText("Channel 5");

        chname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chname3ActionPerformed(evt);
            }
        });

        Lang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Hindi", "Punjabi", "Bangla", "Marathi", "Malayalam", "Kannada", "Gujarati", "Bhojpuri", "Telugu", "Multi Lingual" }));

        BL1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Broadcaster", "Local Channel" }));

        jLabel1.setText("Ala Carte");

        jLabel2.setText("Master SID");

        Lang2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Hindi", "Punjabi", "Bangla", "Marathi", "Malayalam", "Kannada", "Gujarati", "Bhojpuri", "Telugu", "Multi Lingual" }));

        Lang3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Hindi", "Punjabi", "Bangla", "Marathi", "Malayalam", "Kannada", "Gujarati", "Bhojpuri", "Telugu", "Multi Lingual" }));

        Lang4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Hindi", "Punjabi", "Bangla", "Marathi", "Malayalam", "Kannada", "Gujarati", "Bhojpuri", "Telugu", "Multi Lingual" }));

        Lang5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "English", "Hindi", "Punjabi", "Bangla", "Marathi", "Malayalam", "Kannada", "Gujarati", "Bhojpuri", "Telugu", "Multi Lingual" }));

        BL2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Broadcaster", "Local Channel" }));

        BL3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Broadcaster", "Local Channel" }));

        BL4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Broadcaster", "Local Channel" }));

        BL5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Broadcaster", "Local Channel" }));

        jLabel3.setText("Language");

        jLabel4.setText("Broadcaster / Local Channel");

        jLabel5.setText("Channel Name");

        jLabel6.setText("Genre");

        jLabel7.setText("Pay / FTA");

        payfta1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pay", "FTA" }));

        payfta2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pay", "FTA" }));

        payfta3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pay", "FTA" }));
        payfta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payfta3ActionPerformed(evt);
            }
        });

        payfta4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pay", "FTA" }));

        payfta5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pay", "FTA" }));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Ga1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G1", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G2", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G3", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Ga2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G1", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G2", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gc2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G3", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Ga3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G1", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G2", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gc3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G3", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Ga4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G1", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G2", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gc4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G3", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Ga5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G1", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G2", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        Gc5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G3", "Movies", "Local Channel", "Kids", "Music", "Entertainment", "News", "HD", "Infotainment", "Spiritual", "Regional" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Channel1)
                                    .addComponent(Channel2)
                                    .addComponent(Channel3)
                                    .addComponent(Channel5)
                                    .addComponent(Channel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chname1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chname5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chname4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chname3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chname2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(116, 116, 116)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ala2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ala4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ala5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(master1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(master2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(master3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(master4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(master5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lang4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lang5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3)))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(BL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(Ga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Gc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addComponent(ala1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ala3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(payfta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payfta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payfta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(payfta4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(payfta5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(mn)
                                .addGap(60, 60, 60)
                                .addComponent(Filemn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ms, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(das)
                                        .addComponent(ndas, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Filedas, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Filendas, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Filems, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mn)
                                    .addComponent(Filemn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ms)
                                    .addComponent(Filems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(Filedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(das)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ndas)
                                            .addComponent(Filendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Channel1)
                            .addComponent(chname1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ala1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(master1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payfta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Channel2)
                            .addComponent(chname2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ala2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(master2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payfta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Channel3)
                                .addComponent(chname3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ala3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(master3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BL3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(payfta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Gb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Gc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ala4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chname4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(master4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lang4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BL4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payfta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Gc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Channel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ala5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chname5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Channel5))
                    .addComponent(master5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lang5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BL5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(payfta5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Gb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Gc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        Filendas.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msActionPerformed

    private void chname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chname3ActionPerformed

    private void payfta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payfta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payfta3ActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        //for(int i=1; i<=5;i++)
        {
            if(mn.isSelected())
                operationmaster(Filemn.getText());
            if(ms.isSelected())
                operationmaster(Filems.getText());
            if(das.isSelected())
                operationca(Filedas.getText());
            if(ndas.isSelected())
                operationca(Filendas.getText());
            
            
                //JOptionPane.showMessageDialog(mn, "Select Something!!!");
        }
    }//GEN-LAST:event_AddActionPerformed

    private void FilemnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilemnMouseClicked
        // TODO add your handling code here:
        JFileChooser choser = new JFileChooser();
        choser.showOpenDialog(null);
        //nondasFile = choser.getSelectedFile().toString();
        Filemn.setText(choser.getSelectedFile().toString());
    }//GEN-LAST:event_FilemnMouseClicked

    private void FiledasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiledasMouseClicked
        // TODO add your handling code here:
        JFileChooser choser = new JFileChooser();
        choser.showOpenDialog(null);
        //nondasFile = choser.getSelectedFile().toString();
        Filedas.setText(choser.getSelectedFile().toString());
    }//GEN-LAST:event_FiledasMouseClicked

    private void FilendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilendasMouseClicked
        // TODO add your handling code here:
        JFileChooser choser = new JFileChooser();
        choser.showOpenDialog(null);
        //nondasFile = choser.getSelectedFile().toString();
        Filendas.setText(choser.getSelectedFile().toString());
    }//GEN-LAST:event_FilendasMouseClicked

    private void FilemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilemsMouseClicked
        // TODO add your handling code here:
        JFileChooser choser = new JFileChooser();
        choser.showOpenDialog(null);
        //nondasFile = choser.getSelectedFile().toString();
        Filems.setText(choser.getSelectedFile().toString());
    }//GEN-LAST:event_FilemsMouseClicked

    public void operationca(String file)
    {
    try {
            XSSFWorkbook wb = new XSSFWorkbook(file);
            if(Channel1.isSelected())
                writ(wb, chname1.getText(), ala1.getText(), BL1.getSelectedItem().toString(), payfta1.getSelectedItem().toString());
            if(Channel2.isSelected())
                writ(wb, chname2.getText(), ala2.getText(), BL2.getSelectedItem().toString(), payfta2.getSelectedItem().toString());
            if(Channel3.isSelected())
                writ(wb, chname3.getText(), ala3.getText(), BL3.getSelectedItem().toString(), payfta3.getSelectedItem().toString());
            if(Channel4.isSelected())
                writ(wb, chname4.getText(), ala4.getText(), BL4.getSelectedItem().toString(), payfta4.getSelectedItem().toString());
            if(Channel5.isSelected())
                writ(wb, chname5.getText(), ala5.getText(), BL5.getSelectedItem().toString(), payfta5.getSelectedItem().toString());
            
            
            wb.write(new FileOutputStream(file+"_New.xlsx"));
        } catch (IOException ex) {
            Logger.getLogger(Masteradd.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    
    public XSSFWorkbook writ(XSSFWorkbook wb, String chname, String ala, String blc, String pfta)
    {
        if(chname.isEmpty())
            JOptionPane.showMessageDialog(null, "Kindly Mention Channel Name!!!!!");
        else
        {
        XSSFSheet sheet = wb.getSheet("Master List");
        int last = sheet.getLastRowNum();
        System.out.println("1");
        //int i = Integer.parseInt(sheet.getRow(last).getCell(0).getNumericCellValue());
        XSSFCellStyle styl = sheet.getRow(last).getCell(0).getCellStyle();
            sheet.createRow(last+1).createCell(0).setCellValue(sheet.getRow(last).getCell(0).getNumericCellValue()+1);
            sheet.getRow(last+1).getCell(0).setCellStyle(styl);
            System.out.println("2");
            sheet.getRow(last+1).createCell(1).setCellValue(chname);
            sheet.getRow(last+1).getCell(1).setCellStyle(styl);
            sheet.getRow(last+1).createCell(3).setCellStyle(styl);
            System.out.println("3");
            sheet.getRow(last+1).createCell(4).setCellValue(ala);
            sheet.getRow(last+1).getCell(4).setCellStyle(styl);
            sheet.getRow(last+1).createCell(5).setCellValue(blc);
            sheet.getRow(last+1).getCell(5).setCellStyle(styl);
            sheet.getRow(last+1).createCell(6).setCellValue(pfta);
            sheet.getRow(last+1).getCell(6).setCellStyle(styl);
            //sheet.getRow(last+1).setRowStyle(sheet.getRow(last).getRowStyle());
            System.out.println("writing data");
        }
        return wb;
        
    }
    public void operationmaster(String file)
    {
    try {
            XSSFWorkbook wb = new XSSFWorkbook(file);
            if(Channel1.isSelected())
                writ2(wb, chname1.getText(), ala1.getText(), master1.getText(), Ga1.getSelectedItem().toString(), Gb1.getSelectedItem().toString(), Gc1.getSelectedItem().toString(), Lang1.getSelectedItem().toString());
            if(Channel2.isSelected())
                writ2(wb, chname2.getText(), ala2.getText(), master2.getText(), Ga2.getSelectedItem().toString(), Gb2.getSelectedItem().toString(), Gc2.getSelectedItem().toString(), Lang2.getSelectedItem().toString());
            if(Channel3.isSelected())
                writ2(wb, chname3.getText(), ala3.getText(), master3.getText(), Ga3.getSelectedItem().toString(), Gb3.getSelectedItem().toString(), Gc3.getSelectedItem().toString(), Lang3.getSelectedItem().toString());
            if(Channel4.isSelected())
                writ2(wb, chname4.getText(), ala4.getText(), master4.getText(), Ga4.getSelectedItem().toString(), Gb4.getSelectedItem().toString(), Gc4.getSelectedItem().toString(), Lang4.getSelectedItem().toString());
            if(Channel5.isSelected())
                writ2(wb, chname5.getText(), ala5.getText(), master5.getText(), Ga5.getSelectedItem().toString(), Gb5.getSelectedItem().toString(), Gc5.getSelectedItem().toString(), Lang5.getSelectedItem().toString());
            
            
            wb.write(new FileOutputStream(file+"_New.xlsx"));
        } catch (IOException ex) {
            Logger.getLogger(Masteradd.class.getName()).log(Level.SEVERE, null, ex);
       }
        
    }
    public XSSFWorkbook writ2(XSSFWorkbook wb, String chname, String ala, String master, String g1, String g2, String g3, String lang)
    {
        if(chname.isEmpty()||master.isEmpty())
            JOptionPane.showMessageDialog(null, "Kindly Mention Channel Name and Master SID!!!!!");
        else if(master.isEmpty())
            JOptionPane.showMessageDialog(null, "Kindly Mention Master SID!!!!!");
        else
        {
        XSSFSheet sheet = wb.getSheetAt(1);
        String[] sh = sheet.getSheetName().split("-");
        int last = sheet.getLastRowNum();
        System.out.println("1");
        if(g1=="G1")
            g1="";
        if(g2=="G2")
            g2="";
        if(g3=="G3")
            g3="";
        //int i = Integer.parseInt(sheet.getRow(last).getCell(0).getNumericCellValue());
        XSSFCellStyle styl = sheet.getRow(last).getCell(1).getCellStyle();
            sheet.createRow(last+1).createCell(0).setCellValue(last+1);
            System.out.println("2");
            sheet.getRow(last+1).createCell(1).setCellValue(chname);
            sheet.getRow(last+1).createCell(2).setCellValue(ala);
            sheet.getRow(last+1).createCell(3).setCellValue(master);
            System.out.println("3");
            sheet.getRow(last+1).createCell(4).setCellValue(g1);
            sheet.getRow(last+1).createCell(5).setCellValue(g2);
            sheet.getRow(last+1).createCell(6).setCellValue(g3);
            sheet.getRow(last+1).createCell(7).setCellValue(lang);
            for(int s = 0;s<=7;s++)
                sheet.getRow(last+1).getCell(s).setCellStyle(styl);
            for(int s = 8;s<=11;s++)
                sheet.getRow(last+1).createCell(s).setCellStyle(styl);
            //sheet.getRow(last+1).setRowStyle(sheet.getRow(last).getRowStyle());
            System.out.println("writing data");
            wb.setSheetName(1, sh[0]+"-"+(last+1));
        }
        return wb;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masteradd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masteradd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masteradd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masteradd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Masteradd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JComboBox BL1;
    private javax.swing.JComboBox BL2;
    private javax.swing.JComboBox BL3;
    private javax.swing.JComboBox BL4;
    private javax.swing.JComboBox BL5;
    private javax.swing.JCheckBox Channel1;
    private javax.swing.JCheckBox Channel2;
    private javax.swing.JCheckBox Channel3;
    private javax.swing.JCheckBox Channel4;
    private javax.swing.JCheckBox Channel5;
    private javax.swing.JCheckBox Entertainment;
    private javax.swing.JTextField Filedas;
    private javax.swing.JTextField Filemn;
    private javax.swing.JTextField Filems;
    private javax.swing.JTextField Filendas;
    private javax.swing.JComboBox Ga1;
    private javax.swing.JComboBox Ga2;
    private javax.swing.JComboBox Ga3;
    private javax.swing.JComboBox Ga4;
    private javax.swing.JComboBox Ga5;
    private javax.swing.JComboBox Gb1;
    private javax.swing.JComboBox Gb2;
    private javax.swing.JComboBox Gb3;
    private javax.swing.JComboBox Gb4;
    private javax.swing.JComboBox Gb5;
    private javax.swing.JComboBox Gc1;
    private javax.swing.JComboBox Gc2;
    private javax.swing.JComboBox Gc3;
    private javax.swing.JComboBox Gc4;
    private javax.swing.JComboBox Gc5;
    private javax.swing.JCheckBox HD;
    private javax.swing.JCheckBox Infotainment;
    private javax.swing.JCheckBox Kids;
    private javax.swing.JCheckBox LChannel;
    private javax.swing.JComboBox Lang1;
    private javax.swing.JComboBox Lang2;
    private javax.swing.JComboBox Lang3;
    private javax.swing.JComboBox Lang4;
    private javax.swing.JComboBox Lang5;
    private javax.swing.JCheckBox Movies;
    private javax.swing.JCheckBox Music;
    private javax.swing.JCheckBox News;
    private javax.swing.JCheckBox Regional;
    private javax.swing.JCheckBox Spiritual;
    private javax.swing.JTextField ala1;
    private javax.swing.JTextField ala2;
    private javax.swing.JTextField ala3;
    private javax.swing.JTextField ala4;
    private javax.swing.JTextField ala5;
    private javax.swing.JTextField chname1;
    private javax.swing.JTextField chname2;
    private javax.swing.JTextField chname3;
    private javax.swing.JTextField chname4;
    private javax.swing.JTextField chname5;
    private javax.swing.JCheckBox das;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPopupMenu jpmenu;
    private javax.swing.JTextField master1;
    private javax.swing.JTextField master2;
    private javax.swing.JTextField master3;
    private javax.swing.JTextField master4;
    private javax.swing.JTextField master5;
    private javax.swing.JCheckBox mn;
    private javax.swing.JCheckBox ms;
    private javax.swing.JCheckBox ndas;
    private javax.swing.JComboBox payfta1;
    private javax.swing.JComboBox payfta2;
    private javax.swing.JComboBox payfta3;
    private javax.swing.JComboBox payfta4;
    private javax.swing.JComboBox payfta5;
    // End of variables declaration//GEN-END:variables
}
